  name: PowerWorld v2
  main: com.azura4k.PowerWorld.PowerWorldMain
  version: "2.0"
  api: ["1.0.5"]
  author: Azura4k
  commands:
    wand:
      description: "Get World Edit Wand"
      usage: "/Wand. Make sure you have no items in hand"
      permission: "powerworld.cmd.admin"
  permissions:
    powerworld.cmd.admin:
      description: "Ability to use all powerworld commands"
      default: false